### ISSUE TITLE
TODO list 

### ISSUE THREAD

**Issue by trixas97** [trixas97/AutoNet#15]
### Beta version release
This list of features must be done by **22/5/2022**  to be ready to release the first beta version:

**Dashboard page**: 
- [x] Implement the traffic box for networks

**Devices page**:
- [x] Fix the traffic average of each device
- [ ] Fix the delete device functionality on server to delete the reference of device in every topology which includes it.
- [x] Implement the functionality of delete device

**Profile page**:
- [x] Implement the page
- [x] In the page, the user must be can change the username and the password (this is the only feature must be done on beta version for the Profile page)

**Device page**:
- [ ] Fix the bug of traffic. Maybe this bug is only on the last device
- [ ] Implement the protocols box
- [x] Informations => Implement the functionality of privilege password and configuration password text boxes or remove them
- [x] Console => Increase the size of the console window
- [x] Configurations => Implement the functionality of the download and save buttons

**Topology page**:
- [x] Implement double click event for nodes to go to device page after user double click on node

**Network Scan page**:
- [x] Fix the bugs of page

**Server bugs**:
- [x] Implement the functionality when the execution of python scripts failed to stop crash the service. If the server can not connect to device then the device is off
